# Generated by Django 4.1.6 on 2023-02-08 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Flight name')),
                ('price', models.IntegerField(verbose_name='Flight price')),
                ('currency', models.CharField(max_length=20)),
                ('travel_time', models.BigIntegerField(verbose_name='Travel time')),
                ('availability', models.PositiveSmallIntegerField(verbose_name='Available seat count')),
                ('local_departure', models.BigIntegerField(verbose_name='Local departure time')),
                ('deep_link', models.CharField(max_length=1000)),
                ('from_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_from_country_set', to='countries.country', verbose_name='From country')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_flight_set', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('to_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_to_country_set', to='countries.country', verbose_name='To country')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ['price'],
            },
        ),
    ]
