# Generated by Django 4.1.6 on 2023-02-08 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countries', '0001_initial'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='currency',
        ),
        migrations.AddField(
            model_name='flight',
            name='from_airport',
            field=models.CharField(max_length=50, null=True, verbose_name='From airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='from_city',
            field=models.CharField(max_length=50, null=True, verbose_name='From city'),
        ),
        migrations.AddField(
            model_name='flight',
            name='to_airport',
            field=models.CharField(max_length=50, null=True, verbose_name='To airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_flight_set', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='availability',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Available seat count'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='from_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_from_country_set', to='countries.country', verbose_name='From country'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='local_departure',
            field=models.BigIntegerField(null=True, verbose_name='Local departure time'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Flight name'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='to_city',
            field=models.CharField(max_length=50, null=True, verbose_name='To city'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='to_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_to_country_set', to='countries.country', verbose_name='To country'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='travel_time',
            field=models.BigIntegerField(null=True, verbose_name='Travel time'),
        ),
    ]
